name: First Workflow
on: [push]

jobs:
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps:
            - name: echo a strinng
              run: echo "Hello World"
            - name: Multilie command
              run: |
                node -v
                npm -v


                
