name: working dirs & shells

on: 
  push:

defaults: 
    run:
        shell: bash
        # working-directory: de/ed

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Display Working directory and List files
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working Dir
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display Working directory and List files
        run: |
          cd
          dir
          echo %GITHUB_SHA%
          echo %GITHUB_REPOSITORY%
          echo %GITHUB_WORKSPACE%
      - name: Pytho Shell
        shell: python
        run: |
            import platform
            print(platform.processor())
