name: Workflow commands
on: [push]

jobs: 
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting and error message
              run: echo "::error::This is an error message"
            - name: Setting an error message with params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=8::Missing semicolon\""
            - name: Setting and debug message
              run: echo "::debug::This is an error message"
            - name: Setting an debgu message with params
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=8::Missing semicolon"
            - name: Setting and warning message
              run: echo "::warning::This is an error message"
            - name: Setting an debgu message with params
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=8::Missing semicolon"

            