name: Workflow commands
on: [push]

jobs: 
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting and error message
              run: |
                echo "::error::This is an error message"
